### ISSUE TITLE
zlib depends on gcc_linux-64 v10*

### ISSUE THREAD

**Issue by ekomarova** [conda-forge/zlib-feedstock#70]
### Comment:

Because zlib depends on gcc v10*:
`        "build_number": 4,`
`        "build_string": "h166bdaf_4",`
`        "channel": "conda_channel",`
`        "dist_name": "zlib-1.2.13-h166bdaf_4", `
`        "name": "zlib", `
`        "platform": "linux-64", `
`        "version": "1.2.13",`
`        "dependencies": [`
`            "gcc_linux-64 10.*"`
`        ], `
 this can cause conflicts with components that depend on gcc v11*, if try to collect these packages in the one environment and install the dependencies needed for the tests, such as the compiler.
Is it possible to rebuild zlib with gcc 11*?

**Comment by isuruf** [comment]
I don't know where you got this zlib package, but it's certainly not from conda-forge. Please give the details asked in the issue template and make sure you are using conda-forge.

**Comment by ekomarova** [comment]
This is the package from conda-forge: https://anaconda.org/conda-forge/zlib/1.2.13/download/linux-64/zlib-1.2.13-h166bdaf_4.tar.bz2
And its rendered recipe shows that exactly gcc v10* id needed:
`  requires:`
`    - gcc_linux-64 10.*`

**Comment by ekomarova** [comment]
@isuruf Please reopen this issue

**Comment by isuruf** [comment]
You are omitting information from your comments.
Looking at the lines surrounding it, we only require `gcc_linux-64 10.*` in test. Why do you care about a dependency in test?
```
test:
  commands:
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test -f ${PREFIX}/include/zlib.h
  files:
    - test_compile_flags.bat
    - test_compile_flags.c
  requires:
    - gcc_linux-64 10.*
```
