### ISSUE TITLE
inflatePrime missing

### ISSUE THREAD

**Issue by mxmlnkn** [conda-forge/zlib-feedstock#77]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

While [trying to add](https://github.com/conda-forge/staged-recipes/pull/23901#discussion_r1412849624) my package, which depends on zlib, I found that the conda-packaged zlib version seems to be missing the `inflatePrime` symbol. I get:

    undefined symbol: inflatePrime

Out of interest, I tried to do a `find /miniconda3/ -iname '*zlib*so'` and `nm /miniconda3/lib/python3.10/lib-dynload/zlib.cpython-310-x86_64-linux-gnu.so | grep -i inflate` and got the output:

```
                 U inflate
                 U inflateCopy@ZLIB_1.2.0
                 U inflateEnd
                 U inflateInit2_
                 U inflateSetDictionary
00000000000045ff t set_inflate_zdict
```

`inflatePrime` simply seems to be missing, even though it should be there since zlib version 1.2.2.4, which was released in 2005.

### Installed packages

```shell
conda list
# packages in environment at /miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
beautifulsoup4            4.12.2          py310h06a4308_0  
boltons                   23.0.0          py310h06a4308_0  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3  
chardet                   4.0.0           py310h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310h06a4308_0  
conda                     23.7.3          py310h06a4308_0  
conda-build               3.26.1          py310h06a4308_0  
conda-content-trust       0.1.3           py310h06a4308_0  
conda-index               0.2.3           py310h06a4308_0  
conda-package-handling    2.2.0           py310h06a4308_0  
conda-package-streaming   0.9.0           py310h06a4308_0  
cryptography              41.0.2          py310h22a60cf_0  
cxxopts                   3.1.0                hf52228f_0    conda-forge
filelock                  3.9.0           py310h06a4308_0  
glob2                     0.7                pyhd3eb1b0_0  
icu                       73.1                 h6a678d5_0  
idna                      3.4             py310h06a4308_0  
jinja2                    3.1.2           py310h06a4308_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
ld_impl_linux-64          2.38                 h1181459_1  
libarchive                3.6.2                h6ac8c49_2  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
liblief                   0.12.3               h6a678d5_0  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxml2                   2.10.4               hf1b16e4_1  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1           py310h7f8727e_0  
more-itertools            8.12.0             pyhd3eb1b0_0  
ncurses                   6.4                  h6a678d5_0  
openssl                   3.0.12               h7f8727e_0  
packaging                 23.1            py310h06a4308_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pip                       22.3.1          py310h06a4308_0  
pkginfo                   1.9.6           py310h06a4308_0  
pluggy                    1.0.0           py310h06a4308_1  
psutil                    5.9.0           py310h5eee18b_0  
py-lief                   0.12.3          py310h6a678d5_0  
pycosat                   0.6.4           py310h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.2.0          py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.12              h955ad1f_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
pytz                      2022.7          py310h06a4308_0  
pyyaml                    6.0             py310h5eee18b_1  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0          py310h06a4308_0  
ruamel.yaml               0.17.21         py310h5eee18b_0  
ruamel.yaml.clib          0.2.6           py310h5eee18b_1  
setuptools                65.6.3          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.4             py310h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1           py310h06a4308_0  
toolz                     0.12.0          py310h06a4308_0  
tqdm                      4.65.0          py310h2f386ee_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16         py310h06a4308_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0          py310h5eee18b_0  
zstd                      1.5.5                hc292b87_0
```

### Environment info

```shell
active environment : base
    active env location : /miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.config/conda/condarc
                          /home/user/.condarc
          conda version : 23.7.3
    conda-build version : 3.26.1
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /miniconda3  (writable)
      conda av data dir : /miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Linux/5.15.0-84-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by carterbox** [comment]
`zlib.cpython-310-x86_64-linux-gnu.so` is not an artifact created by this package. It is a python extension module created by some other package.

`$PREFIX/lib/libz.so` is the shared object created by this package.

```
nm libz.so | grep -i inflate
0000000000009ee0 T inflate
0000000000007850 T inflateBack
0000000000008cb0 T inflateBackEnd
0000000000007740 T inflateBackInit_
000000000000c640 T inflateCodesUsed
000000000000c2b0 T inflateCopy
000000000000bd70 T inflateEnd
000000000000bdd0 T inflateGetDictionary
000000000000bf30 T inflateGetHeader
0000000000009d40 T inflateInit2_
0000000000009e40 T inflateInit_
000000000000c5b0 T inflateMark
0000000000009e50 T inflatePrime   <---- HERE
0000000000009c40 T inflateReset
0000000000009ca0 T inflateReset2
0000000000009b80 T inflateResetKeep
000000000000be80 T inflateSetDictionary
0000000000009b30 t inflateStateCheck
000000000000bfa0 T inflateSync
000000000000c250 T inflateSyncPoint
000000000000c4e0 T inflateUndermine
000000000000c540 T inflateValidate
0000000000015a40 r inflate_copyright
0000000000008cf0 t inflate_fast
000000000000c6b0 t inflate_table
```

Which does contain inflatePrime!

**Comment by ocefpaf** [comment]
Note that in your environment there you are not using conda-forge's zlib. While I did not check, I'm pretty sure that the defaults package also contains that symbol. However, issues opened here should be about the conda-forge package only.

**Comment by mxmlnkn** [comment]
Thank you for your help. I was not aware that I was using the wrong one (though it still is weird that inflatePrime is missing there). But, how do I use the conda-forge zlib? My meta.yaml looks like this:

```yaml
{% set name = "rapidgzip" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidgzip-{{ version }}.tar.gz
  sha256: 7535504f1ce08c7014ba8580dbe6ac308e60d9f216bc7125e3a6dd4c803102f8
  patches:
    - configure-dependencies.patch

build:
  entry_points:
    - rapidgzip=rapidgzip:cli
  script_env:
    - RAPIDGZIP_BUILD_CXXOPTS=system
    - RAPIDGZIP_BUILD_ISAL=disabled
    - RAPIDGZIP_BUILD_RPMALLOC=enabled
    - RAPIDGZIP_BUILD_ZLIB=system
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - nasm
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2
  host:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - python
    - setuptools >=46.4.0
    - wheel
    - cython >=0.29.24
    - pip
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
    - python
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2

test:
  imports:
    - rapidgzip
  commands:
    - pip check
    - rapidgzip --help
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/rapidgzip
  summary: Parallel random access to gzip files
  license: BSD-3-Clause AND Unlicense AND BSD-2-Clause AND Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
```

Do I have to set the requirements to something like `conda-zlib` instead of `zlib`?

Edit: Or, I guess, I'll have to check my setup.py as to how it looks for shared libraries.
